### ISSUE TITLE
效果较差

### ISSUE THREAD

**Issue by lucasjinreal** [AtomEcho/AtomGPT#14]
![image](https://github.com/AtomEcho/AtomGPT/assets/21303438/d70d13e9-c685-45b9-b3d6-b759e0456db5)

跟是不是int4似乎没有关系，我试过openbuddy的int4，非常智能。

感觉还是有不小的差距。

**Comment by ZHangZHengEric** [comment]
感谢关注
当前模型在数学计算上的表现确实比较差。主要原因还是预训练数据的分布占据比较大的原因。当前的预训练数据基本上不会有逻辑计算相关的东西。目前的目标确实也不再数学计算上。
如果有什么想法，可以一起来优化实现。

**Comment by lucasjinreal** [comment]
主要是如果按照这种状态，比较难做精准的langchain或者下游任务。

我认为预训练的影响得加入一些数学、代码尽可能包罗万象的数据，然后在sft阶段混入少量数学数据，虽然不可能百分百正确，但比没有好，13b的学习上限不应该止步于此

**Comment by ZHangZHengEric** [comment]
赞同
目前看预训练的过程，应该逐步的训练了一些代码数据了。针对数学的暂时没有找到比较好的数据。可以给提供一些建议，非常感谢。
在整个训练的过程中，已经基本体现出来，预训练是模型能力的核心了。

最后，非常感谢给出的建议

**Comment by lucasjinreal** [comment]
@ZHangZHengEric 我没有试过直接测试13b的生成模型的生成能力，在sft之前一个好的底座比较关键，可以参考baichuan的底座重点测一下各方面指标。再比如一些直观的续写的能力，续写基础指令理解能力。
sft其实都比较趋同，随便搞一搞都能高出比较好的效果。

**Comment by ZHangZHengEric** [comment]
关于预训练模型，测试确实是非常重要的环节，可惜目前人手有点紧张。
sft想要搞出好的效果，还是非常依赖预训练模型的，如果预训练模型比较差，sft的效果也不会太好，比如知识的宽度上。
sft也就使用了50k的训练数据，这些训练数据并不会给模型带来知识以及能力的增加。只是做了分布的映射。

以上个人拙见，欢迎大佬们一起沟通讨论。

**Comment by lucasjinreal** [comment]
@ZHangZHengEric 我想邀请大佬加入一个国产大模型微信交流群，一来推广一下你们的atomgpt，二来看看和其他模型的对比反馈，三来看看有没有机会一起合作优化。
![6e419822a85bc13f01fed9cf601836f](https://github.com/AtomEcho/AtomGPT/assets/21303438/1dd87f92-6aaa-4c1b-a394-4e68a5be053d)
