### ISSUE TITLE
关于28000step的模型数据

### ISSUE THREAD

**Issue by 44670** [AtomEcho/AtomGPT#15]
你好，我在 https://grow.atomecho.cn/ 上看到了最新的测试结果，是基于28000 step的。

请问，这个ckpt的数据大概会在什么时候上传呢？看上去比14000要好很多。

谢谢

**Comment by ZHangZHengEric** [comment]
28k的应该近期，会更新上。目前还在测试28k的一些问题。
感谢关注

**Comment by 44670** [comment]
非常感谢你们的工作。

另外我想了解一下，你们的模型的License是什么呢？

**Comment by ZHangZHengEric** [comment]
[Apache-2.0 license](https://github.com/AtomEcho/AtomGPT/blob/main/LICENSE)

**Comment by 44670** [comment]
非常感谢！
