### ISSUE TITLE
关于预训练进度的问题

### ISSUE THREAD

**Issue by nuoma** [AtomEcho/AtomGPT#34]
你好，首先恭喜非常solid的work！

我想问一下第56000步，约等于你们计划中1T语料的几个epoch？
因为不知道你们其他的超参数，无法估计目前训练的进度，是不是起码要等1个epoch完成以后拿去评估比如ceval cmmlu才会比较好。

另，很奇怪为什么大家都喜欢用step来形容训练进度而不是epoch呢？

**Comment by ZHangZHengEric** [comment]
因为距离1个epoch 还有很大的距离，最近机器分配到其他的一些地方，就更慢了一些。
