### ISSUE TITLE
全量微调的对话模型

### ISSUE THREAD

**Issue by 44670** [AtomEcho/AtomGPT#35]
你好，我们基于AtomEcho 56k的ckpt，基于我们的方法，全量微调了一个对话型模型，效果看上去还可以：

模型地址：https://huggingface.co/OpenBuddy/openbuddy-atom-13b-v9-bf16

测试报告：https://huggingface.co/OpenBuddy/openbuddy-atom-13b-v9-bf16/blob/main/Evaluation.txt

似乎具备一定的认知能力，但是计算能力似乎还是不太行，是否和预训练的数据集有关系呢？

我们也会继续尝试解决计算方面的问题。

**Comment by ZHangZHengEric** [comment]
对，预训练数据营销比较大啊，目前预训练数学知识，或者说数字token 添加的很少。
感谢基于我们的模型进行了优化
